### ISSUE TITLE
jsdelivr CDN is missing chartjs-adapter-moment@0.1.0 

### ISSUE THREAD

**Issue by jung-kim** [chartjs/chartjs-adapter-moment#12]
Hi, thanks for all the hard works and I'm exited for the 3.0.0 and forward.

In current document, https://cdn.jsdelivr.net/npm/chartjs-adapter-moment@0.1.0 is listed but it seems that doesn't exist in jsdelivr, however v0.1.1 does exist.

will this be a common practice to remove older version until project becomes more stable?  or is this just a mishap?

**Comment by benmccann** [comment]
We didn't remove anything. It's possible it never got published in the first place though. We don't manage `jsdelivr`. I'm not sure how they decide when to pick up a library
