### ISSUE TITLE
Doesn't work with chart.js 3.0.0-beta.3

### ISSUE THREAD

**Issue by MatthiasGrandl** [chartjs/chartjs-adapter-moment#20]
`Error: "time" is not a registered scale.`

**Comment by benmccann** [comment]
This isn't an issue with the adapter, but with your usage of chart.js. Did you register the time scale before trying to use it?

**Comment by MatthiasGrandl** [comment]
I guess you're right, but I honestly can't figure out from the migration guide how to do that...

**Comment by kurkle** [comment]
> I guess you're right, but I honestly can't figure out from the migration guide how to do that...

Take a look there: https://www.chartjs.org/docs/master/getting-started/v3-migration/#setup-and-installation

**Comment by MatthiasGrandl** [comment]
Nevermind figured it out after reading the source code :)

**Comment by kdekooter** [comment]
> If you are using the time or timeseries scales, you must include one of the available adapters and corresponding date library.

Great. But how does one _include_ it?? 
Can you enlighten us @MatthiasGrandl @kurkle ?
