### ISSUE TITLE
TypeError: Cannot read property '_date' of undefined when using Chartjs 3.x.x

### ISSUE THREAD

**Issue by esttenorio** [chartjs/chartjs-adapter-moment#26]
The import on the index.js seems to fail when using in a typescript project.

![image](https://user-images.githubusercontent.com/8483207/110396032-1c7c0580-8024-11eb-97f4-cb66323b5b28.png)
![image](https://user-images.githubusercontent.com/8483207/110396000-0ec68000-8024-11eb-9088-52963cc518b9.png)

After locally changing from `import {Chart} from 'chart.js';` to `import * as Chart from 'chart.js';` the extension works again.

https://github.com/chartjs/Chart.js/blob/7ec99c38c1b41b16cf7cad433569af56c2544d63/types/index.esm.d.ts#L25

I checked the charts repo and the adapters are separate. There's no default export of ChartJs so the fix is:
- update ChartJs ts exports so Chart is the default export
- on this adapter change the import to `import * as Chart from 'chart.js';`
or
- on this adapter change the import to `import {_adapter} from 'chart.js';

**Comment by etimberg** [comment]
Was this fixed in v1.0.0-beta.1? https://github.com/chartjs/chartjs-adapter-moment/releases/tag/v1.0.0-beta.1

**Comment by esttenorio** [comment]
no, that's precisely the package I'm using:

"chartjs-adapter-moment": "^1.0.0-beta.1",

**Comment by etimberg** [comment]
Ah, ok. I thought I had fixed it. Will take another look. Does `import {_adapters} from 'chart.js';` work for you?

**Comment by esttenorio** [comment]
Thanks for publishing a new version with a fix so quickly 👍
